TestDB_1:
    hostName: localhost
    userName: root
    passWord: gc
    dbPort: 3306
    dbName: gc1
TestDB_2:
    hostName: localhost
    userName: root
    passWord: gc
    dbPort: 3306
    dbName: gc2

